### ISSUE TITLE
Iphone 11,6 iOS 12.0.1

### ISSUE THREAD

**Issue by itssm312** [razmashat/voucher_swap#2]
I added my offset and it worked 

 { "iPhone11,6", "16A40-16A405", offsets__iphone11_8__16C50},

**Comment by LucaTomei1995** [comment]
Sorry, how can I find my offset?

**Comment by itssm312** [comment]
DM me on twitter ill explain there @manisafiyari @LucaTomei1995

**Comment by razmashat** [comment]
Added offsets for all iPhones A10+ closeing that issue now
